config/routes.rb
Rails.application.routes.draw do
  root 'cryptos#index'

  resources :cryptos

  get "load" => "cryptos#load"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  # Méthode si on souhaite utiliser un text-field pour la recherche
  def index
    @cryptos = (params[:search].nil?) ? nil : Crypto.find(params[:search])
  end

  def load
    StartScrap.new.perform
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/index.html.erb
<center>
<h1>Liste des crypto-monnaies</h1>
<%= form_tag(cryptos_path, method: :get) do %>
  <%= select_tag "search", options_from_collection_for_select(Crypto.all, 'id', 'name') %>
  <%= submit_tag "Search", name: nil %>
<% end %><br/>

<% if(!@cryptos.nil?)%>
    <p>Le cours du <strong><%= @cryptos.name %></strong> est de <strong><%= @cryptos.value %></strong></p>  <!-- Avec un select_tag il n'est pas la peine de définir un params car celui-ci est automatiquement définit, il faut donc utiliser ce params (ici id mais renvoie le name en affichage) pour aller chercher dans la BDD -->
<%end%>

</center>

app/views/cryptos/load.html.erb
<h1> Les données ont été chargées </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServicesLyonX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>